### PR TITLE
Fix: configs for ENSO

### PR DESCRIPTION
**Pull request by gaozhihan**
*Issue #5*

Fix the [cfg.yaml](https://github.com/amazon-research/earth-forecasting-transformer/blob/61cab363c8c15d98ecd40643d628303d0234096b/scripts/cuboid_transformer/enso/cfg.yaml) for training on ENSO.
1. Change `total_batch_size: 32` to `total_batch_size: 64` to reproduce the reported results in our paper. `total_batch_size: 32` results in [suboptimal performance](https://tensorboard.dev/experiment/2rl0nEmoRdWB8wgdeHYk5Q/#scalars&_smoothingWeight=0), while `total_batch_size: 64` [works correctly](https://tensorboard.dev/experiment/Jwq47eRfRoqO8kv2qCRqdA/#scalars&_smoothingWeight=0).
2. Delete unused config `data_seq_len`

### CODE REVIEW

**Comment by sxjscience** [comment]
We need to also exchange the metric names in https://github.com/amazon-research/earth-forecasting-transformer/blob/61cab363c8c15d98ecd40643d628303d0234096b/scripts/cuboid_transformer/enso/train_cuboid_enso.py#L533-L534

- `valid_acc` --> `valid_corr_nino3.4`
- `valid_weighted_acc` --> `valid_corr_nino3.4_weighted`.

**Comment by sxjscience** [comment]
Also, change accordingly the test_acc / test_weighted_acc --> https://github.com/amazon-research/earth-forecasting-transformer/blob/61cab363c8c15d98ecd40643d628303d0234096b/scripts/cuboid_transformer/enso/train_cuboid_enso.py#L577-L578

**Comment by gaozhihan** [comment]
> We need to also exchange the metric names in
> 
> https://github.com/amazon-research/earth-forecasting-transformer/blob/61cab363c8c15d98ecd40643d628303d0234096b/scripts/cuboid_transformer/enso/train_cuboid_enso.py#L533-L534
> 
> * `valid_acc` --> `valid_corr_nino3.4`
> * `valid_weighted_acc` --> `valid_corr_nino3.4_weighted`.

Done

**Review by sxjscience — APPROVED** [review]
Thanks! We can later try the optimization techniques in xformers so that we can use larger batch size.

**Comment by sxjscience** [comment]
Also, we need to add test cases...

**Pull request merged**
